### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [arsvechkarev/Vault#54]
[diff.html.zip](https://github.com/arsvechkarev/Vault/files/14133754/diff.html.zip)

It seems the only diff is that pg-map-id is different. Could you please take a look? Thanks!

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/6294030022#L4384

your local tool versions is different?

**Comment by arsvechkarev** [comment]
If I understand correctly, tool versions i=gradle version? If yes, then it is true, my gradle version is 8.5. Should I update it for the build to pass?

**Comment by linsui** [comment]
It's easy to fix. But the apk is still not reproducible. https://gitlab.com/linsui/fdroiddata/-/jobs/6306448147

**Comment by licaon-kter** [comment]
diffing the APKs from the CI above and the released one

there's a difference in baseline, and a difference in classes.dex

upon dissembling classes.dex via apktool the smali files are identical, oddly enough :shrug: 

trying directly:
```
$ diffoscope classes.dex classes-2.dex
--- classes.dex
+++ classes-2.dex
├── dexdump -a -d -f -h {}
│┄ Ignoring differences in offsets to keep diff size reasonable.
│ @@ -1,12 +1,12 @@
│  DEX version '038'
│  DEX file header:
│  magic               : 'dex\n038\0'
│ -checksum            : 07e5bdb3
│ -signature           : 1974...2f40
│ +checksum            : 0011bd77
│ +signature           : 71bb...b505
│  file_size           : 1979640
│  header_size         : 112
│  link_size           : 0
│  link_off            : 0 (0x000000)
│  string_ids_size     : 11985
│  string_ids_off      : 112 (0x000070)
│  type_ids_size       : 3388
```

@arsvechkarev can you clean caches, gradle caches, etc and rebuild the APK?

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15403
